apiVersion: v1
kind: ConfigMap
metadata:
  name: shortline-config
data:
  BASE_URL: "http://shortline.default.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: shortline-secret
type: Opaque
stringData:
  API_KEY: "demo-key-change-me"
