apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shortline
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: shortline
  endpoints:
    - port: http
      path: /metrics
